# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuilderPromotionInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BuilderPromotionInfo.proto',
  package='NewConstruction',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\017NewConstruction\242\002\027ProtobufNewConstruction'),
  serialized_pb=_b('\n\x1a\x42uilderPromotionInfo.proto\x12\x0fNewConstruction\"=\n\x14\x42uilderPromotionInfo\x12\x10\n\x08headline\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\tBJ\n\x1d\x63om.zillow.mobile.webservicesB\x0fNewConstruction\xa2\x02\x17ProtobufNewConstruction')
)




_BUILDERPROMOTIONINFO = _descriptor.Descriptor(
  name='BuilderPromotionInfo',
  full_name='NewConstruction.BuilderPromotionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headline', full_name='NewConstruction.BuilderPromotionInfo.headline', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='NewConstruction.BuilderPromotionInfo.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['BuilderPromotionInfo'] = _BUILDERPROMOTIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuilderPromotionInfo = _reflection.GeneratedProtocolMessageType('BuilderPromotionInfo', (_message.Message,), dict(
  DESCRIPTOR = _BUILDERPROMOTIONINFO,
  __module__ = 'BuilderPromotionInfo_pb2'
  # @@protoc_insertion_point(class_scope:NewConstruction.BuilderPromotionInfo)
  ))
_sym_db.RegisterMessage(BuilderPromotionInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
