# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HomeTypes.proto',
  package='HomeTypes',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\tHomeTypes\242\002\014ProtobufHome'),
  serialized_pb=_b('\n\x0fHomeTypes.proto\x12\tHomeTypes\"\xcb\x01\n\x0eListingSubType\x12\x0f\n\x07is_FSBO\x18\x01 \x01(\x08\x12\x12\n\nis_pending\x18\x02 \x01(\x08\x12\x12\n\nis_newHome\x18\x03 \x01(\x08\x12\x16\n\x0eis_foreclosure\x18\x04 \x01(\x08\x12\x14\n\x0cis_bankOwned\x18\x05 \x01(\x08\x12\x15\n\ris_forAuction\x18\x06 \x01(\x08\x12\x0e\n\x06is_SOL\x18\x07 \x01(\x08\x12\x14\n\x0cis_openHouse\x18\x08 \x01(\x08\x12\x15\n\ris_comingSoon\x18\t \x01(\x08\x42\x39\n\x1d\x63om.zillow.mobile.webservicesB\tHomeTypes\xa2\x02\x0cProtobufHome')
)




_LISTINGSUBTYPE = _descriptor.Descriptor(
  name='ListingSubType',
  full_name='HomeTypes.ListingSubType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_FSBO', full_name='HomeTypes.ListingSubType.is_FSBO', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_pending', full_name='HomeTypes.ListingSubType.is_pending', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_newHome', full_name='HomeTypes.ListingSubType.is_newHome', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_foreclosure', full_name='HomeTypes.ListingSubType.is_foreclosure', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_bankOwned', full_name='HomeTypes.ListingSubType.is_bankOwned', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_forAuction', full_name='HomeTypes.ListingSubType.is_forAuction', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_SOL', full_name='HomeTypes.ListingSubType.is_SOL', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_openHouse', full_name='HomeTypes.ListingSubType.is_openHouse', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_comingSoon', full_name='HomeTypes.ListingSubType.is_comingSoon', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['ListingSubType'] = _LISTINGSUBTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListingSubType = _reflection.GeneratedProtocolMessageType('ListingSubType', (_message.Message,), dict(
  DESCRIPTOR = _LISTINGSUBTYPE,
  __module__ = 'HomeTypes_pb2'
  # @@protoc_insertion_point(class_scope:HomeTypes.ListingSubType)
  ))
_sym_db.RegisterMessage(ListingSubType)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
