# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HomeDetails.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python_proto import PropertyImageResults_pb2 as PropertyImageResults__pb2
from python_proto import VideoDetailsResults_pb2 as VideoDetailsResults__pb2
from python_proto import VrModelDisplayDetailsResults_pb2 as VrModelDisplayDetailsResults__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='HomeDetails.proto',
  package='HomeDetails',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\013HomeDetails\242\002\010Protobuf'),
  serialized_pb=_b('\n\x11HomeDetails.proto\x12\x0bHomeDetails\x1a\x1aPropertyImageResults.proto\x1a\x19VideoDetailsResults.proto\x1a\"VrModelDisplayDetailsResults.proto\"\xec\x01\n\x10HomeMediaDetails\x12?\n\x0cimageResults\x18\x01 \x01(\x0b\x32).PropertyImageResults.PropertyImageResult\x12=\n\x0cvideoResults\x18\x02 \x01(\x0b\x32\'.VideoDetailsResults.VideoDetailsResult\x12X\n\x15vrModelDisplayResults\x18\x03 \x01(\x0b\x32\x39.VrModelDisplayDetailsResults.VrModelDisplayDetailsResult\"\'\n\x0cInstantOffer\x12\x17\n\x0finstantOfferUrl\x18\x01 \x01(\t\"\xdb\x01\n\x11HomeDetailsResult\x12\x12\n\napiVersion\x18\x01 \x02(\x05\x12\x14\n\x0cresponseCode\x18\x02 \x02(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12\x33\n\x0cmediaDetails\x18\x04 \x01(\x0b\x32\x1d.HomeDetails.HomeMediaDetails\x12\x1d\n\x15hdpTemplateJsonString\x18\x05 \x01(\t\x12/\n\x0cinstantOffer\x18\x06 \x01(\x0b\x32\x19.HomeDetails.InstantOfferB7\n\x1d\x63om.zillow.mobile.webservicesB\x0bHomeDetails\xa2\x02\x08Protobuf')
  ,
  dependencies=[PropertyImageResults__pb2.DESCRIPTOR,VideoDetailsResults__pb2.DESCRIPTOR,VrModelDisplayDetailsResults__pb2.DESCRIPTOR,])




_HOMEMEDIADETAILS = _descriptor.Descriptor(
  name='HomeMediaDetails',
  full_name='HomeDetails.HomeMediaDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageResults', full_name='HomeDetails.HomeMediaDetails.imageResults', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videoResults', full_name='HomeDetails.HomeMediaDetails.videoResults', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vrModelDisplayResults', full_name='HomeDetails.HomeMediaDetails.vrModelDisplayResults', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=362,
)


_INSTANTOFFER = _descriptor.Descriptor(
  name='InstantOffer',
  full_name='HomeDetails.InstantOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instantOfferUrl', full_name='HomeDetails.InstantOffer.instantOfferUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=403,
)


_HOMEDETAILSRESULT = _descriptor.Descriptor(
  name='HomeDetailsResult',
  full_name='HomeDetails.HomeDetailsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='HomeDetails.HomeDetailsResult.apiVersion', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='HomeDetails.HomeDetailsResult.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='HomeDetails.HomeDetailsResult.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mediaDetails', full_name='HomeDetails.HomeDetailsResult.mediaDetails', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hdpTemplateJsonString', full_name='HomeDetails.HomeDetailsResult.hdpTemplateJsonString', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instantOffer', full_name='HomeDetails.HomeDetailsResult.instantOffer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=625,
)

_HOMEMEDIADETAILS.fields_by_name['imageResults'].message_type = PropertyImageResults__pb2._PROPERTYIMAGERESULT
_HOMEMEDIADETAILS.fields_by_name['videoResults'].message_type = VideoDetailsResults__pb2._VIDEODETAILSRESULT
_HOMEMEDIADETAILS.fields_by_name['vrModelDisplayResults'].message_type = VrModelDisplayDetailsResults__pb2._VRMODELDISPLAYDETAILSRESULT
_HOMEDETAILSRESULT.fields_by_name['mediaDetails'].message_type = _HOMEMEDIADETAILS
_HOMEDETAILSRESULT.fields_by_name['instantOffer'].message_type = _INSTANTOFFER
DESCRIPTOR.message_types_by_name['HomeMediaDetails'] = _HOMEMEDIADETAILS
DESCRIPTOR.message_types_by_name['InstantOffer'] = _INSTANTOFFER
DESCRIPTOR.message_types_by_name['HomeDetailsResult'] = _HOMEDETAILSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HomeMediaDetails = _reflection.GeneratedProtocolMessageType('HomeMediaDetails', (_message.Message,), dict(
  DESCRIPTOR = _HOMEMEDIADETAILS,
  __module__ = 'HomeDetails_pb2'
  # @@protoc_insertion_point(class_scope:HomeDetails.HomeMediaDetails)
  ))
_sym_db.RegisterMessage(HomeMediaDetails)

InstantOffer = _reflection.GeneratedProtocolMessageType('InstantOffer', (_message.Message,), dict(
  DESCRIPTOR = _INSTANTOFFER,
  __module__ = 'HomeDetails_pb2'
  # @@protoc_insertion_point(class_scope:HomeDetails.InstantOffer)
  ))
_sym_db.RegisterMessage(InstantOffer)

HomeDetailsResult = _reflection.GeneratedProtocolMessageType('HomeDetailsResult', (_message.Message,), dict(
  DESCRIPTOR = _HOMEDETAILSRESULT,
  __module__ = 'HomeDetails_pb2'
  # @@protoc_insertion_point(class_scope:HomeDetails.HomeDetailsResult)
  ))
_sym_db.RegisterMessage(HomeDetailsResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
