# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocationLookup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python_proto import HomeInfo_pb2 as HomeInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LocationLookup.proto',
  package='LocationAPI',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\016LocationLookup\242\002\010Protobuf'),
  serialized_pb=_b('\n\x14LocationLookup.proto\x12\x0bLocationAPI\x1a\x0eHomeInfo.proto\"G\n\x06Region\x12\x10\n\x08regionId\x18\x01 \x02(\x05\x12+\n\nregionType\x18\x02 \x02(\x0e\x32\x17.LocationAPI.RegionType\"?\n\x1eLocationDisambiguationHomeList\x12\x1d\n\x05homes\x18\x01 \x03(\x0b\x32\x0e.HomeInfo.Home\"\xa6\x02\n\x0eLocationResult\x12\x12\n\napiVersion\x18\x01 \x02(\x05\x12\x14\n\x0cresponseCode\x18\x02 \x02(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12\x15\n\rwestLongitude\x18\x04 \x01(\x01\x12\x15\n\rsouthLatitude\x18\x05 \x01(\x01\x12\x15\n\reastLongitude\x18\x06 \x01(\x01\x12\x15\n\rnorthLatitude\x18\x07 \x01(\x01\x12P\n\x1blocationDisambiguationHomes\x18\x08 \x01(\x0b\x32+.LocationAPI.LocationDisambiguationHomeList\x12#\n\x06region\x18\t \x01(\x0b\x32\x13.LocationAPI.Region*\xbc\x02\n\nRegionType\x12\r\n\tcontinent\x10\x00\x12\x0b\n\x07\x63ountry\x10\x01\x12\t\n\x05state\x10\x02\x12\n\n\x06\x63ounty\x10\x04\x12\x08\n\x04\x63ity\x10\x06\x12\x0b\n\x07zipcode\x10\x07\x12\x0b\n\x07\x62orough\x10\x11\x12\x10\n\x0cneighborhood\x10\x08\x12\x08\n\x04\x66lex\x10\x1f\x12\t\n\x05place\x10\t\x12\x0c\n\x07unknown\x10\xff\x01\x12\x0f\n\x0bsubdivision\x10\x13\x12\r\n\tcommunity\x10\x12\x12\t\n\x05metro\x10\x0e\x12\x07\n\x03\x64ma\x10\n\x12\x12\n\x0eschoolDistrict\x10\x15\x12\x14\n\x10\x65lementarySchool\x10\x16\x12\x10\n\x0cmiddleSchool\x10\x17\x12\x0e\n\nhighSchool\x10\x18\x12\x12\n\x0eschoolFragment\x10\x19\x12\x0e\n\nuniversity\x10\x1a\x42:\n\x1d\x63om.zillow.mobile.webservicesB\x0eLocationLookup\xa2\x02\x08Protobuf')
  ,
  dependencies=[HomeInfo__pb2.DESCRIPTOR,])

_REGIONTYPE = _descriptor.EnumDescriptor(
  name='RegionType',
  full_name='LocationAPI.RegionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='continent', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='country', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='state', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='county', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='city', index=4, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='zipcode', index=5, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='borough', index=6, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='neighborhood', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='flex', index=8, number=31,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='place', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unknown', index=10, number=255,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='subdivision', index=11, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='community', index=12, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='metro', index=13, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='dma', index=14, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='schoolDistrict', index=15, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='elementarySchool', index=16, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='middleSchool', index=17, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='highSchool', index=18, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='schoolFragment', index=19, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='university', index=20, number=26,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=489,
  serialized_end=805,
)
_sym_db.RegisterEnumDescriptor(_REGIONTYPE)

RegionType = enum_type_wrapper.EnumTypeWrapper(_REGIONTYPE)
continent = 0
country = 1
state = 2
county = 4
city = 6
zipcode = 7
borough = 17
neighborhood = 8
flex = 31
place = 9
unknown = 255
subdivision = 19
community = 18
metro = 14
dma = 10
schoolDistrict = 21
elementarySchool = 22
middleSchool = 23
highSchool = 24
schoolFragment = 25
university = 26



_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='LocationAPI.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regionId', full_name='LocationAPI.Region.regionId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regionType', full_name='LocationAPI.Region.regionType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=124,
)


_LOCATIONDISAMBIGUATIONHOMELIST = _descriptor.Descriptor(
  name='LocationDisambiguationHomeList',
  full_name='LocationAPI.LocationDisambiguationHomeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='homes', full_name='LocationAPI.LocationDisambiguationHomeList.homes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=189,
)


_LOCATIONRESULT = _descriptor.Descriptor(
  name='LocationResult',
  full_name='LocationAPI.LocationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='LocationAPI.LocationResult.apiVersion', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='LocationAPI.LocationResult.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='LocationAPI.LocationResult.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='westLongitude', full_name='LocationAPI.LocationResult.westLongitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='southLatitude', full_name='LocationAPI.LocationResult.southLatitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eastLongitude', full_name='LocationAPI.LocationResult.eastLongitude', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northLatitude', full_name='LocationAPI.LocationResult.northLatitude', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locationDisambiguationHomes', full_name='LocationAPI.LocationResult.locationDisambiguationHomes', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='LocationAPI.LocationResult.region', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=486,
)

_REGION.fields_by_name['regionType'].enum_type = _REGIONTYPE
_LOCATIONDISAMBIGUATIONHOMELIST.fields_by_name['homes'].message_type = HomeInfo__pb2._HOME
_LOCATIONRESULT.fields_by_name['locationDisambiguationHomes'].message_type = _LOCATIONDISAMBIGUATIONHOMELIST
_LOCATIONRESULT.fields_by_name['region'].message_type = _REGION
DESCRIPTOR.message_types_by_name['Region'] = _REGION
DESCRIPTOR.message_types_by_name['LocationDisambiguationHomeList'] = _LOCATIONDISAMBIGUATIONHOMELIST
DESCRIPTOR.message_types_by_name['LocationResult'] = _LOCATIONRESULT
DESCRIPTOR.enum_types_by_name['RegionType'] = _REGIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), dict(
  DESCRIPTOR = _REGION,
  __module__ = 'LocationLookup_pb2'
  # @@protoc_insertion_point(class_scope:LocationAPI.Region)
  ))
_sym_db.RegisterMessage(Region)

LocationDisambiguationHomeList = _reflection.GeneratedProtocolMessageType('LocationDisambiguationHomeList', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONDISAMBIGUATIONHOMELIST,
  __module__ = 'LocationLookup_pb2'
  # @@protoc_insertion_point(class_scope:LocationAPI.LocationDisambiguationHomeList)
  ))
_sym_db.RegisterMessage(LocationDisambiguationHomeList)

LocationResult = _reflection.GeneratedProtocolMessageType('LocationResult', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONRESULT,
  __module__ = 'LocationLookup_pb2'
  # @@protoc_insertion_point(class_scope:LocationAPI.LocationResult)
  ))
_sym_db.RegisterMessage(LocationResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
