# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PropertyImageListResults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python_proto import PropertyImageResults_pb2 as PropertyImageResults__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PropertyImageListResults.proto',
  package='GetPropertyImagesListResults',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\030PropertyImageListResults\242\002\010Protobuf'),
  serialized_pb=_b('\n\x1ePropertyImageListResults.proto\x12\x1cGetPropertyImagesListResults\x1a\x1aPropertyImageResults.proto\"\xc2\x01\n\x11PropertyImageList\x12\x0c\n\x04zpid\x18\x01 \x02(\x05\x12+\n\x06images\x18\x02 \x03(\x0b\x32\x1b.PropertyImageResults.Image\x12:\n\rhighResImages\x18\x03 \x01(\x0b\x32#.PropertyImageResults.HighResImages\x12\x36\n\x0bwatchImages\x18\x04 \x01(\x0b\x32!.PropertyImageResults.WatchImages\"\x95\x01\n\x10ImageListResults\x12\x12\n\napiVersion\x18\x01 \x02(\x05\x12\x14\n\x0cresponseCode\x18\x02 \x02(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12>\n\x05homes\x18\x04 \x03(\x0b\x32/.GetPropertyImagesListResults.PropertyImageListBD\n\x1d\x63om.zillow.mobile.webservicesB\x18PropertyImageListResults\xa2\x02\x08Protobuf')
  ,
  dependencies=[PropertyImageResults__pb2.DESCRIPTOR,])




_PROPERTYIMAGELIST = _descriptor.Descriptor(
  name='PropertyImageList',
  full_name='GetPropertyImagesListResults.PropertyImageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zpid', full_name='GetPropertyImagesListResults.PropertyImageList.zpid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='GetPropertyImagesListResults.PropertyImageList.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='highResImages', full_name='GetPropertyImagesListResults.PropertyImageList.highResImages', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='watchImages', full_name='GetPropertyImagesListResults.PropertyImageList.watchImages', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=287,
)


_IMAGELISTRESULTS = _descriptor.Descriptor(
  name='ImageListResults',
  full_name='GetPropertyImagesListResults.ImageListResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='GetPropertyImagesListResults.ImageListResults.apiVersion', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='GetPropertyImagesListResults.ImageListResults.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='GetPropertyImagesListResults.ImageListResults.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homes', full_name='GetPropertyImagesListResults.ImageListResults.homes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=439,
)

_PROPERTYIMAGELIST.fields_by_name['images'].message_type = PropertyImageResults__pb2._IMAGE
_PROPERTYIMAGELIST.fields_by_name['highResImages'].message_type = PropertyImageResults__pb2._HIGHRESIMAGES
_PROPERTYIMAGELIST.fields_by_name['watchImages'].message_type = PropertyImageResults__pb2._WATCHIMAGES
_IMAGELISTRESULTS.fields_by_name['homes'].message_type = _PROPERTYIMAGELIST
DESCRIPTOR.message_types_by_name['PropertyImageList'] = _PROPERTYIMAGELIST
DESCRIPTOR.message_types_by_name['ImageListResults'] = _IMAGELISTRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropertyImageList = _reflection.GeneratedProtocolMessageType('PropertyImageList', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTYIMAGELIST,
  __module__ = 'PropertyImageListResults_pb2'
  # @@protoc_insertion_point(class_scope:GetPropertyImagesListResults.PropertyImageList)
  ))
_sym_db.RegisterMessage(PropertyImageList)

ImageListResults = _reflection.GeneratedProtocolMessageType('ImageListResults', (_message.Message,), dict(
  DESCRIPTOR = _IMAGELISTRESULTS,
  __module__ = 'PropertyImageListResults_pb2'
  # @@protoc_insertion_point(class_scope:GetPropertyImagesListResults.ImageListResults)
  ))
_sym_db.RegisterMessage(ImageListResults)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
