# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoDetailsResults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from python_proto import PropertyImageResults_pb2 as PropertyImageResults__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoDetailsResults.proto',
  package='VideoDetailsResults',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\023VideoDetailsResults\242\002\010Protobuf'),
  serialized_pb=_b('\n\x19VideoDetailsResults.proto\x12\x13VideoDetailsResults\x1a\x1aPropertyImageResults.proto\"@\n\x12VideoDetailsResult\x12*\n\x06videos\x18\x01 \x03(\x0b\x32\x1a.VideoDetailsResults.Video\"\xe3\x02\n\x05Video\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.VideoDetailsResults.Video.VideoStatusType\x12\x14\n\x0chlsStreamUrl\x18\x02 \x01(\t\x12/\n\ncoverImage\x18\x03 \x01(\x0b\x32\x1b.PropertyImageResults.Image\x12\x15\n\rpublisherName\x18\x04 \x01(\t\x12\x19\n\x11publisherImageUrl\x18\x05 \x01(\t\x12\x16\n\x0e\x63reateDateTime\x18\x06 \x01(\x03\x12\x16\n\x0evideoIdEncoded\x18\x07 \x01(\t\x12\x16\n\x0eisVideoCreator\x18\x08 \x01(\x08\"]\n\x0fVideoStatusType\x12\t\n\x05\x44RAFT\x10\x00\x12\n\n\x06PUBLIC\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x0b\n\x07PRIVATE\x10\x03\x12\x0b\n\x07\x44\x45LETED\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x42?\n\x1d\x63om.zillow.mobile.webservicesB\x13VideoDetailsResults\xa2\x02\x08Protobuf')
  ,
  dependencies=[PropertyImageResults__pb2.DESCRIPTOR,])



_VIDEO_VIDEOSTATUSTYPE = _descriptor.EnumDescriptor(
  name='VideoStatusType',
  full_name='VideoDetailsResults.Video.VideoStatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DRAFT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=500,
)
_sym_db.RegisterEnumDescriptor(_VIDEO_VIDEOSTATUSTYPE)


_VIDEODETAILSRESULT = _descriptor.Descriptor(
  name='VideoDetailsResult',
  full_name='VideoDetailsResults.VideoDetailsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videos', full_name='VideoDetailsResults.VideoDetailsResult.videos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=142,
)


_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='VideoDetailsResults.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='VideoDetailsResults.Video.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hlsStreamUrl', full_name='VideoDetailsResults.Video.hlsStreamUrl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coverImage', full_name='VideoDetailsResults.Video.coverImage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisherName', full_name='VideoDetailsResults.Video.publisherName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisherImageUrl', full_name='VideoDetailsResults.Video.publisherImageUrl', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createDateTime', full_name='VideoDetailsResults.Video.createDateTime', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='videoIdEncoded', full_name='VideoDetailsResults.Video.videoIdEncoded', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isVideoCreator', full_name='VideoDetailsResults.Video.isVideoCreator', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEO_VIDEOSTATUSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=500,
)

_VIDEODETAILSRESULT.fields_by_name['videos'].message_type = _VIDEO
_VIDEO.fields_by_name['status'].enum_type = _VIDEO_VIDEOSTATUSTYPE
_VIDEO.fields_by_name['coverImage'].message_type = PropertyImageResults__pb2._IMAGE
_VIDEO_VIDEOSTATUSTYPE.containing_type = _VIDEO
DESCRIPTOR.message_types_by_name['VideoDetailsResult'] = _VIDEODETAILSRESULT
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoDetailsResult = _reflection.GeneratedProtocolMessageType('VideoDetailsResult', (_message.Message,), dict(
  DESCRIPTOR = _VIDEODETAILSRESULT,
  __module__ = 'VideoDetailsResults_pb2'
  # @@protoc_insertion_point(class_scope:VideoDetailsResults.VideoDetailsResult)
  ))
_sym_db.RegisterMessage(VideoDetailsResult)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), dict(
  DESCRIPTOR = _VIDEO,
  __module__ = 'VideoDetailsResults_pb2'
  # @@protoc_insertion_point(class_scope:VideoDetailsResults.Video)
  ))
_sym_db.RegisterMessage(Video)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
