# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetZRectResults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from python_proto import HomeInfo_pb2 as HomeInfo__pb2,\
    SchoolInfo_pb2 as SchoolInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetZRectResults.proto',
  package='GetZRectResults',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\017GetZRectResults\242\002\020ProtobufGetZRect'),
  serialized_pb=_b('\n\x15GetZRectResults.proto\x12\x0fGetZRectResults\x1a\x0eHomeInfo.proto\x1a\x10SchoolInfo.proto\"\xa1\x02\n\x07Results\x12\x12\n\napiVersion\x18\x01 \x02(\x05\x12\x14\n\x0cresponseCode\x18\x02 \x02(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12\x12\n\npageNumber\x18\x04 \x01(\x05\x12\x12\n\ntotalHomes\x18\x05 \x01(\x05\x12\x15\n\rfmrTotalHomes\x18\x06 \x01(\x05\x12\x10\n\x08\x61\x64\x43ounty\x18\x07 \x01(\t\x12)\n\x05homes\x18\x08 \x03(\x0b\x32\x1a.GetZRectResults.HomeParts\x12\x0b\n\x03\x64ma\x18\t \x01(\t\x12\x0f\n\x07ordinal\x18\n \x01(\x03\x12\x39\n\x13schoolSearchResults\x18\x0b \x01(\x0b\x32\x1c.Schools.SchoolSearchResults\";\n\tHomeParts\x12\x0f\n\x07unknown\x18\x01 \x02(\x05\x12\x1d\n\x05homes\x18\x02 \x03(\x0b\x32\x0e.HomeInfo.HomeBC\n\x1d\x63om.zillow.mobile.webservicesB\x0fGetZRectResults\xa2\x02\x10ProtobufGetZRect')
  ,
  dependencies=[HomeInfo__pb2.DESCRIPTOR,SchoolInfo__pb2.DESCRIPTOR,])




_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='GetZRectResults.Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='GetZRectResults.Results.apiVersion', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='GetZRectResults.Results.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='GetZRectResults.Results.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageNumber', full_name='GetZRectResults.Results.pageNumber', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalHomes', full_name='GetZRectResults.Results.totalHomes', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fmrTotalHomes', full_name='GetZRectResults.Results.fmrTotalHomes', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adCounty', full_name='GetZRectResults.Results.adCounty', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homes', full_name='GetZRectResults.Results.homes', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dma', full_name='GetZRectResults.Results.dma', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ordinal', full_name='GetZRectResults.Results.ordinal', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolSearchResults', full_name='GetZRectResults.Results.schoolSearchResults', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=366,
)


_HOMEPARTS = _descriptor.Descriptor(
  name='HomeParts',
  full_name='GetZRectResults.HomeParts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown', full_name='GetZRectResults.HomeParts.unknown', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='homes', full_name='GetZRectResults.HomeParts.homes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=427,
)

_RESULTS.fields_by_name['homes'].message_type = _HOMEPARTS
_RESULTS.fields_by_name['schoolSearchResults'].message_type = SchoolInfo__pb2._SCHOOLSEARCHRESULTS
_HOMEPARTS.fields_by_name['homes'].message_type = HomeInfo__pb2._HOME
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
DESCRIPTOR.message_types_by_name['HomeParts'] = _HOMEPARTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), dict(
  DESCRIPTOR = _RESULTS,
  __module__ = 'GetZRectResults_pb2'
  # @@protoc_insertion_point(class_scope:GetZRectResults.Results)
  ))
_sym_db.RegisterMessage(Results)

HomeParts = _reflection.GeneratedProtocolMessageType('HomeParts', (_message.Message,), dict(
  DESCRIPTOR = _HOMEPARTS,
  __module__ = 'GetZRectResults_pb2'
  # @@protoc_insertion_point(class_scope:GetZRectResults.HomeParts)
  ))
_sym_db.RegisterMessage(HomeParts)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
