# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenHouseDetails.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenHouseDetails.proto',
  package='OpenHouseDetails',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\020OpenHouseDetails\242\002\010Protobuf'),
  serialized_pb=_b('\n\x16OpenHouseDetails.proto\x12\x10OpenHouseDetails\"O\n\rOpenHouseInfo\x12>\n\x12open_house_showing\x18\x01 \x03(\x0b\x32\".OpenHouseDetails.OpenHouseShowing\"D\n\x10OpenHouseShowing\x12\x18\n\x10open_house_start\x18\x01 \x01(\x03\x12\x16\n\x0eopen_house_end\x18\x02 \x01(\x03\x42<\n\x1d\x63om.zillow.mobile.webservicesB\x10OpenHouseDetails\xa2\x02\x08Protobuf')
)




_OPENHOUSEINFO = _descriptor.Descriptor(
  name='OpenHouseInfo',
  full_name='OpenHouseDetails.OpenHouseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_house_showing', full_name='OpenHouseDetails.OpenHouseInfo.open_house_showing', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=123,
)


_OPENHOUSESHOWING = _descriptor.Descriptor(
  name='OpenHouseShowing',
  full_name='OpenHouseDetails.OpenHouseShowing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_house_start', full_name='OpenHouseDetails.OpenHouseShowing.open_house_start', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_house_end', full_name='OpenHouseDetails.OpenHouseShowing.open_house_end', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=193,
)

_OPENHOUSEINFO.fields_by_name['open_house_showing'].message_type = _OPENHOUSESHOWING
DESCRIPTOR.message_types_by_name['OpenHouseInfo'] = _OPENHOUSEINFO
DESCRIPTOR.message_types_by_name['OpenHouseShowing'] = _OPENHOUSESHOWING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenHouseInfo = _reflection.GeneratedProtocolMessageType('OpenHouseInfo', (_message.Message,), dict(
  DESCRIPTOR = _OPENHOUSEINFO,
  __module__ = 'OpenHouseDetails_pb2'
  # @@protoc_insertion_point(class_scope:OpenHouseDetails.OpenHouseInfo)
  ))
_sym_db.RegisterMessage(OpenHouseInfo)

OpenHouseShowing = _reflection.GeneratedProtocolMessageType('OpenHouseShowing', (_message.Message,), dict(
  DESCRIPTOR = _OPENHOUSESHOWING,
  __module__ = 'OpenHouseDetails_pb2'
  # @@protoc_insertion_point(class_scope:OpenHouseDetails.OpenHouseShowing)
  ))
_sym_db.RegisterMessage(OpenHouseShowing)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
