# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PropertyImageResults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PropertyImageResults.proto',
  package='PropertyImageResults',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\024PropertyImageResults\242\002\010Protobuf'),
  serialized_pb=_b('\n\x1aPropertyImageResults.proto\x12\x14PropertyImageResults\"\xcd\x01\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x0f\n\x07imageId\x18\x03 \x01(\t\x12\x12\n\nhighResUrl\x18\x04 \x01(\t\x12\x10\n\x08is_owner\x18\x05 \x01(\x08\x12\x12\n\nis_private\x18\x06 \x01(\x08\x12\x0f\n\x07subject\x18\x07 \x01(\t\x12\x10\n\x08watchUrl\x18\x08 \x01(\t\x12\r\n\x05tvUrl\x18\t \x01(\t\x12\x17\n\x0ftvCollectionUrl\x18\n \x01(\t\x12\x10\n\x08tvHdpUrl\x18\x0b \x01(\t\"<\n\rHighResImages\x12+\n\x06images\x18\x01 \x03(\x0b\x32\x1b.PropertyImageResults.Image\":\n\x0bWatchImages\x12+\n\x06images\x18\x01 \x03(\x0b\x32\x1b.PropertyImageResults.Image\"\x87\x02\n\x13PropertyImageResult\x12\x12\n\napiVersion\x18\x01 \x02(\x05\x12\x14\n\x0cresponseCode\x18\x02 \x02(\x05\x12\x17\n\x0fresponseMessage\x18\x03 \x01(\t\x12+\n\x06images\x18\x04 \x03(\x0b\x32\x1b.PropertyImageResults.Image\x12:\n\rhighResImages\x18\x05 \x01(\x0b\x32#.PropertyImageResults.HighResImages\x12\x0c\n\x04zpid\x18\x06 \x01(\t\x12\x36\n\x0bwatchImages\x18\x07 \x01(\x0b\x32!.PropertyImageResults.WatchImagesB@\n\x1d\x63om.zillow.mobile.webservicesB\x14PropertyImageResults\xa2\x02\x08Protobuf')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='PropertyImageResults.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='PropertyImageResults.Image.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='caption', full_name='PropertyImageResults.Image.caption', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageId', full_name='PropertyImageResults.Image.imageId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='highResUrl', full_name='PropertyImageResults.Image.highResUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_owner', full_name='PropertyImageResults.Image.is_owner', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_private', full_name='PropertyImageResults.Image.is_private', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='PropertyImageResults.Image.subject', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='watchUrl', full_name='PropertyImageResults.Image.watchUrl', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tvUrl', full_name='PropertyImageResults.Image.tvUrl', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tvCollectionUrl', full_name='PropertyImageResults.Image.tvCollectionUrl', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tvHdpUrl', full_name='PropertyImageResults.Image.tvHdpUrl', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=258,
)


_HIGHRESIMAGES = _descriptor.Descriptor(
  name='HighResImages',
  full_name='PropertyImageResults.HighResImages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='PropertyImageResults.HighResImages.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=320,
)


_WATCHIMAGES = _descriptor.Descriptor(
  name='WatchImages',
  full_name='PropertyImageResults.WatchImages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='PropertyImageResults.WatchImages.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=380,
)


_PROPERTYIMAGERESULT = _descriptor.Descriptor(
  name='PropertyImageResult',
  full_name='PropertyImageResults.PropertyImageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='PropertyImageResults.PropertyImageResult.apiVersion', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseCode', full_name='PropertyImageResults.PropertyImageResult.responseCode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='PropertyImageResults.PropertyImageResult.responseMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='PropertyImageResults.PropertyImageResult.images', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='highResImages', full_name='PropertyImageResults.PropertyImageResult.highResImages', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zpid', full_name='PropertyImageResults.PropertyImageResult.zpid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='watchImages', full_name='PropertyImageResults.PropertyImageResult.watchImages', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=646,
)

_HIGHRESIMAGES.fields_by_name['images'].message_type = _IMAGE
_WATCHIMAGES.fields_by_name['images'].message_type = _IMAGE
_PROPERTYIMAGERESULT.fields_by_name['images'].message_type = _IMAGE
_PROPERTYIMAGERESULT.fields_by_name['highResImages'].message_type = _HIGHRESIMAGES
_PROPERTYIMAGERESULT.fields_by_name['watchImages'].message_type = _WATCHIMAGES
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['HighResImages'] = _HIGHRESIMAGES
DESCRIPTOR.message_types_by_name['WatchImages'] = _WATCHIMAGES
DESCRIPTOR.message_types_by_name['PropertyImageResult'] = _PROPERTYIMAGERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'PropertyImageResults_pb2'
  # @@protoc_insertion_point(class_scope:PropertyImageResults.Image)
  ))
_sym_db.RegisterMessage(Image)

HighResImages = _reflection.GeneratedProtocolMessageType('HighResImages', (_message.Message,), dict(
  DESCRIPTOR = _HIGHRESIMAGES,
  __module__ = 'PropertyImageResults_pb2'
  # @@protoc_insertion_point(class_scope:PropertyImageResults.HighResImages)
  ))
_sym_db.RegisterMessage(HighResImages)

WatchImages = _reflection.GeneratedProtocolMessageType('WatchImages', (_message.Message,), dict(
  DESCRIPTOR = _WATCHIMAGES,
  __module__ = 'PropertyImageResults_pb2'
  # @@protoc_insertion_point(class_scope:PropertyImageResults.WatchImages)
  ))
_sym_db.RegisterMessage(WatchImages)

PropertyImageResult = _reflection.GeneratedProtocolMessageType('PropertyImageResult', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTYIMAGERESULT,
  __module__ = 'PropertyImageResults_pb2'
  # @@protoc_insertion_point(class_scope:PropertyImageResults.PropertyImageResult)
  ))
_sym_db.RegisterMessage(PropertyImageResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
