# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RentalInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RentalInfo.proto',
  package='RentalInfo',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\nRentalInfo\242\002\010Protobuf'),
  serialized_pb=_b('\n\x10RentalInfo.proto\x12\nRentalInfo\"\x81\x03\n\x12RentalPropertyInfo\x12\x17\n\x0fin_unit_laundry\x18\x01 \x01(\x08\x12\x18\n\x10\x61ssigned_parking\x18\x02 \x01(\x08\x12=\n\nappliances\x18\x03 \x01(\x0b\x32).RentalInfo.RentalPropertyInfo.Appliances\x12\x19\n\x11income_restricted\x18\x04 \x01(\x08\x12\x18\n\x10\x63ommunity_pillar\x18\x05 \x01(\x08\x1a\xc3\x01\n\nAppliances\x12\x12\n\ndishwasher\x18\x01 \x01(\x08\x12\r\n\x05\x64ryer\x18\x02 \x01(\x08\x12\x0f\n\x07\x66reezer\x18\x03 \x01(\x08\x12\x18\n\x10garbage_disposal\x18\x04 \x01(\x08\x12\x11\n\tmicrowave\x18\x05 \x01(\x08\x12\x15\n\rrange_or_oven\x18\x06 \x01(\x08\x12\x14\n\x0crefrigerator\x18\x07 \x01(\x08\x12\x17\n\x0ftrash_compactor\x18\x08 \x01(\x08\x12\x0e\n\x06washer\x18\t \x01(\x08\x42\x36\n\x1d\x63om.zillow.mobile.webservicesB\nRentalInfo\xa2\x02\x08Protobuf')
)




_RENTALPROPERTYINFO_APPLIANCES = _descriptor.Descriptor(
  name='Appliances',
  full_name='RentalInfo.RentalPropertyInfo.Appliances',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dishwasher', full_name='RentalInfo.RentalPropertyInfo.Appliances.dishwasher', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dryer', full_name='RentalInfo.RentalPropertyInfo.Appliances.dryer', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freezer', full_name='RentalInfo.RentalPropertyInfo.Appliances.freezer', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='garbage_disposal', full_name='RentalInfo.RentalPropertyInfo.Appliances.garbage_disposal', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='microwave', full_name='RentalInfo.RentalPropertyInfo.Appliances.microwave', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_or_oven', full_name='RentalInfo.RentalPropertyInfo.Appliances.range_or_oven', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refrigerator', full_name='RentalInfo.RentalPropertyInfo.Appliances.refrigerator', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trash_compactor', full_name='RentalInfo.RentalPropertyInfo.Appliances.trash_compactor', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='washer', full_name='RentalInfo.RentalPropertyInfo.Appliances.washer', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=418,
)

_RENTALPROPERTYINFO = _descriptor.Descriptor(
  name='RentalPropertyInfo',
  full_name='RentalInfo.RentalPropertyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_unit_laundry', full_name='RentalInfo.RentalPropertyInfo.in_unit_laundry', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assigned_parking', full_name='RentalInfo.RentalPropertyInfo.assigned_parking', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appliances', full_name='RentalInfo.RentalPropertyInfo.appliances', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='income_restricted', full_name='RentalInfo.RentalPropertyInfo.income_restricted', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='community_pillar', full_name='RentalInfo.RentalPropertyInfo.community_pillar', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RENTALPROPERTYINFO_APPLIANCES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=418,
)

_RENTALPROPERTYINFO_APPLIANCES.containing_type = _RENTALPROPERTYINFO
_RENTALPROPERTYINFO.fields_by_name['appliances'].message_type = _RENTALPROPERTYINFO_APPLIANCES
DESCRIPTOR.message_types_by_name['RentalPropertyInfo'] = _RENTALPROPERTYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RentalPropertyInfo = _reflection.GeneratedProtocolMessageType('RentalPropertyInfo', (_message.Message,), dict(

  Appliances = _reflection.GeneratedProtocolMessageType('Appliances', (_message.Message,), dict(
    DESCRIPTOR = _RENTALPROPERTYINFO_APPLIANCES,
    __module__ = 'RentalInfo_pb2'
    # @@protoc_insertion_point(class_scope:RentalInfo.RentalPropertyInfo.Appliances)
    ))
  ,
  DESCRIPTOR = _RENTALPROPERTYINFO,
  __module__ = 'RentalInfo_pb2'
  # @@protoc_insertion_point(class_scope:RentalInfo.RentalPropertyInfo)
  ))
_sym_db.RegisterMessage(RentalPropertyInfo)
_sym_db.RegisterMessage(RentalPropertyInfo.Appliances)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
