# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VrModelDisplayDetailsResults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VrModelDisplayDetailsResults.proto',
  package='VrModelDisplayDetailsResults',
  syntax='proto2',
  serialized_options=_b('\n\035com.zillow.mobile.webservicesB\034VrModelDisplayDetailsResults\242\002\010Protobuf'),
  serialized_pb=_b('\n\"VrModelDisplayDetailsResults.proto\x12\x1cVrModelDisplayDetailsResults\"V\n\x1bVrModelDisplayDetailsResult\x12\x37\n\x08vrModels\x18\x01 \x03(\x0b\x32%.VrModelDisplayDetailsResults.VrModel\"\xff\x02\n\x07VrModel\x12\x13\n\x0b\x61utoApprove\x18\x01 \x01(\x08\x12\x19\n\x11\x63reateDateTimeUtc\x18\x02 \x01(\x03\x12\x13\n\x0b\x63reatorZuid\x18\x03 \x01(\t\x12\x1d\n\x15lastUpdateDateTimeUtc\x18\x04 \x01(\x03\x12\x12\n\nrevisionId\x18\x05 \x01(\t\x12\x15\n\rvrModelIdGuid\x18\x06 \x01(\t\x12\x11\n\tvrModelId\x18\x07 \x01(\t\x12\x44\n\nstatusType\x18\x08 \x01(\x0e\x32\x30.VrModelDisplayDetailsResults.VrModel.StatusType\x12\x0c\n\x04zpid\x18\t \x01(\x05\x12\x11\n\tviewerUrl\x18\n \x01(\t\x12\x0f\n\x07\x63\x64nHost\x18\x0b \x01(\t\"Z\n\nStatusType\x12\x0b\n\x07PRIVATE\x10\x01\x12\t\n\x05\x44RAFT\x10\x02\x12\n\n\x06PUBLIC\x10\x03\x12\x10\n\x0cNOT_EDITABLE\x10\x04\x12\x0b\n\x07\x44\x45LETED\x10\x05\x12\t\n\x05\x45RROR\x10\x64\x42H\n\x1d\x63om.zillow.mobile.webservicesB\x1cVrModelDisplayDetailsResults\xa2\x02\x08Protobuf')
)



_VRMODEL_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='VrModelDisplayDetailsResults.VrModel.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAFT', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_EDITABLE', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=5, number=100,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=450,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_VRMODEL_STATUSTYPE)


_VRMODELDISPLAYDETAILSRESULT = _descriptor.Descriptor(
  name='VrModelDisplayDetailsResult',
  full_name='VrModelDisplayDetailsResults.VrModelDisplayDetailsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vrModels', full_name='VrModelDisplayDetailsResults.VrModelDisplayDetailsResult.vrModels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=154,
)


_VRMODEL = _descriptor.Descriptor(
  name='VrModel',
  full_name='VrModelDisplayDetailsResults.VrModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='autoApprove', full_name='VrModelDisplayDetailsResults.VrModel.autoApprove', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createDateTimeUtc', full_name='VrModelDisplayDetailsResults.VrModel.createDateTimeUtc', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creatorZuid', full_name='VrModelDisplayDetailsResults.VrModel.creatorZuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastUpdateDateTimeUtc', full_name='VrModelDisplayDetailsResults.VrModel.lastUpdateDateTimeUtc', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revisionId', full_name='VrModelDisplayDetailsResults.VrModel.revisionId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vrModelIdGuid', full_name='VrModelDisplayDetailsResults.VrModel.vrModelIdGuid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vrModelId', full_name='VrModelDisplayDetailsResults.VrModel.vrModelId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusType', full_name='VrModelDisplayDetailsResults.VrModel.statusType', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zpid', full_name='VrModelDisplayDetailsResults.VrModel.zpid', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='viewerUrl', full_name='VrModelDisplayDetailsResults.VrModel.viewerUrl', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cdnHost', full_name='VrModelDisplayDetailsResults.VrModel.cdnHost', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VRMODEL_STATUSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=540,
)

_VRMODELDISPLAYDETAILSRESULT.fields_by_name['vrModels'].message_type = _VRMODEL
_VRMODEL.fields_by_name['statusType'].enum_type = _VRMODEL_STATUSTYPE
_VRMODEL_STATUSTYPE.containing_type = _VRMODEL
DESCRIPTOR.message_types_by_name['VrModelDisplayDetailsResult'] = _VRMODELDISPLAYDETAILSRESULT
DESCRIPTOR.message_types_by_name['VrModel'] = _VRMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VrModelDisplayDetailsResult = _reflection.GeneratedProtocolMessageType('VrModelDisplayDetailsResult', (_message.Message,), dict(
  DESCRIPTOR = _VRMODELDISPLAYDETAILSRESULT,
  __module__ = 'VrModelDisplayDetailsResults_pb2'
  # @@protoc_insertion_point(class_scope:VrModelDisplayDetailsResults.VrModelDisplayDetailsResult)
  ))
_sym_db.RegisterMessage(VrModelDisplayDetailsResult)

VrModel = _reflection.GeneratedProtocolMessageType('VrModel', (_message.Message,), dict(
  DESCRIPTOR = _VRMODEL,
  __module__ = 'VrModelDisplayDetailsResults_pb2'
  # @@protoc_insertion_point(class_scope:VrModelDisplayDetailsResults.VrModel)
  ))
_sym_db.RegisterMessage(VrModel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
